### ISSUE TITLE
Compatibility between TweetNacl and TweetNaclFast for Box?

### ISSUE THREAD

**Issue by franks42** [InstantWebP2P/tweetnacl-java#10]
As I understand it, the "Fast" version pre-calculates the DH shared-key and uses that directly for the encryption&signing.
I expected the output from the box() method on the TweetNacl.Box and the TweetNaclFast.Box instances to be compatible, i.e. have the same encrypted message and format, and be interchangeable.

However, I get errors if I mix them up, like in TweetNaclFastTest.java, I added

               import com.iwebpp.crypto.TweetNacl;

and added to the Box test case:

		// peer A -> B
		TweetNaclFast.Box pab = new TweetNaclFast.Box(kb.getPublicKey(), ka.getSecretKey());
		//TweetNacl.Box pab = new TweetNacl.Box(kb.getPublicKey(), ka.getSecretKey());

		// peer B -> A
		TweetNaclFast.Box pba = new TweetNaclFast.Box(ka.getPublicKey(), kb.getSecretKey());
		//TweetNacl.Box pba = new TweetNacl.Box(ka.getPublicKey(), kb.getSecretKey());

If they are compatible, I can mix and match the two classes - uncomment one and comment the other.
However, I get null pointers when I do that.
All ok when I box() and open() with the same version.

Is that a bug? Do I miss anything?

**Comment by sequoiar** [comment]
@franks42 Can you post your test code and test result log detail here ?

**Comment by franks42** [comment]
Please clone the fork I have at "https://github.com/franks42/tweetnacl-java".
There is a new test file "TweetNaclBoxTest.java", which tries to isolate the testcase for the compatibility between fast and slow box/open of a message.
Test run with:

      $ mkdir out
      $ javac -d out src/com/iwebpp/crypto/*.java src/com/iwebpp/crypto/tests/*.java
      $ java -cp out com.iwebpp.crypto.tests.TweetNaclBoxTest

My output shows that fast with fast works, slow with slow works, but mixing them does not:

    $ java -cp out com.iwebpp.crypto.tests.TweetNaclBoxTestTweetNaclBoxTest:debug:start test
    TweetNaclBoxTest:debug:BoxNonce: "3Ld3kBfMFgJIRwdMk4R5j43xUUbVFVXO"
    TweetNaclBoxTest:debug:ska: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    TweetNaclBoxTest:debug:pka: "L-V9o0fNYkMVKNqsX7spBzD_9oSvxM_C7ZCZX1jLO3Q"
    TweetNaclBoxTest:debug:skb: "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE"
    TweetNaclBoxTest:debug:pkb: "pOCSkrZRwni5dyxWn1-puxPZBrRqtoyd-dwrRAn4ogk"
    TweetNaclBoxTest:debug:cabFast: "bPdN9sNzqEuN-n0J9YIJuL_Q_nM7FlOZgR1MCGyJsy-RWNGfFw"
    TweetNaclBoxTest:debug:cabSlow: "LzkL6C_v-IUVaqTA0id5sr_Q_nM7FlOZgR1MCGyJsy-RWNGfFw"
    TweetNaclBoxTest:debug:mbaFastFast: "SGVsbG93b3JkLCBBbSBUb20gLi4u"
    TweetNaclBoxTest:debug:nm0FastFast: "Helloword, Am Tom ..."
    TweetNaclBoxTest:debug:mbaSlowSlow: "SGVsbG93b3JkLCBBbSBUb20gLi4u"
    TweetNaclBoxTest:debug:nm0SlowSlow: "Helloword, Am Tom ..."
    Exception in thread "Thread-0" java.lang.NullPointerException
	at java.util.Base64$Encoder.encode(Base64.java:261)
	at java.util.Base64$Encoder.encodeToString(Base64.java:315)
	at com.iwebpp.crypto.TweetNaclFast.base64EncodeToString(TweetNaclFast.java:3369)
	at com.iwebpp.crypto.tests.TweetNaclBoxTest.testBoxNonce(TweetNaclBoxTest.java:67)
	at com.iwebpp.crypto.tests.TweetNaclBoxTest.access$000(TweetNaclBoxTest.java:9)
	at com.iwebpp.crypto.tests.TweetNaclBoxTest$1.run(TweetNaclBoxTest.java:110)
	at java.lang.Thread.run(Thread.java:745)

Hope this helps...

**Comment by franks42** [comment]
You can actually see from the previous output:

    TweetNaclBoxTest:debug:cabFast: "bPdN9sNzqEuN-n0J9YIJuL_Q_nM7FlOZgR1MCGyJsy-RWNGfFw"
    TweetNaclBoxTest:debug:cabSlow: "LzkL6C_v-IUVaqTA0id5sr_Q_nM7FlOZgR1MCGyJsy-RWNGfFw"

that the right half of the encrypted messages "_Q_nM7FlOZgR1MCGyJsy-RWNGfFw"  is the same, but the left part is not.
If I understand it well, then the right half is the actual encrypted message, and the left is the authentication tag.
That authentication tag may be different for slow and fast... (?)

**Comment by sequoiar** [comment]
@franks42 did you try with explicit Nonce for mixed tests ?

**Comment by franks42** [comment]
Yes - in the mixed test,  the nonce is explicitly past in:

      byte [] mbaFastSlow = pbaFast.open(cabSlow, theNonce);

The encrypted message should be identical for the same key-pairs and the same nonce for both the fast and slow cases. There seems to be a difference in the first part of the encrypted message, which is the authentication tag - hopefully that can guide the debugging.
There are quite a lot of code differences between slow and fast besides simply the pre-calculation of the shared key - difficult for me to follow...
Also, I've made quite a few changes - if the debugging is difficult, you may want to go back a few revisions to see if you can see the same without me having "messed" with the code.

**Comment by franks42** [comment]
Added some of the test vectors from the kalium project from their TestVectors.java file, which list public and private keys, a nonce and a message with its associated cypher text obtained through the equivalent Box.box() operation.

I modified the TweetNaclBoxTest.java to use those test vectors, and the result is... (drumroll...)...: the fast implementation matches the kalium test vectors!

In other words, with some certainty there is a bug somewhere in the "slow" code, most probably in the authentication tag generation.

Clone the last version of the fork I have at "https://github.com/franks42/tweetnacl-java" to see the result.

**Comment by sequoiar** [comment]
@franks42 sounds good on TweetNaclFast.java test result. I will try to fix tweetnacl.java. And, it's better to use TweetNaclFast.java in production, because TweetNacl.java is slower twice than TweetNaclFast.java.

**Comment by franks42** [comment]
Maybe just do away with the slow implementation, and only have one file to maintain - having digged through the code of both,  it seems that the fast implementation code received more love and attention. Consolidate all your efforts on one!
Also, you may want to add some test vectors of the Kalium and libsodium projects to your tests as the basis - it will bring out incompatibilities and bugs sooner.

**Comment by sequoiar** [comment]
I just porting onetiemauth function from TweetNaclFast to TweetNacl. now both are compatible. 
it's really debug sign/unsign operation with java code. 

@franks42 please pull the code, and try it again with your test vector. if ok, please send a pull request. thx.
