### ISSUE TITLE
Randomly brings infinit loop

### ISSUE THREAD

**Issue by legarspol** [InstantWebP2P/tweetnacl-java#13]
Hi !
I'm trying to bring a JS software to java using this lib and I don't know much about all the theory and crypto things it use.

I quite often (1 over 2 try) run into infinite loop while calling: 
public static int crypto_secretbox(byte [] c, byte [] m, int /*long*/ d, byte [] n, byte [] k);

When such infinit loop may occur ?
Would a unit test showing the call with params and the infinit loop in action help ?
Many thanks for your help

**Comment by sequoiar** [comment]
What's your test data? I didn't meet infinite loops.

 And did you use TweetNaclFast.java or TweetNacl.java ?

**Comment by legarspol** [comment]
I'll generate a test in the coming days (ASAP) I use the Fast implementation.

**Comment by legarspol** [comment]
Hi !
It seems it was a problem not related to your implementation.
Sorry for the inconvenience and thank you for your kind support.
