### ISSUE TITLE
keyPair_fromSeed() is insecure/misleading

### ISSUE THREAD

**Issue by ryhaberecht** [InstantWebP2P/tweetnacl-java#14]
public static KeyPair keyPair_fromSeed(byte [] seed) simply takes the seed and uses it as the secret key. This is horribly insecure, because seeds are usually of very little entropy and very predictable.

Therefore, we should either rename the function to something like "keyPair_fromSecretKey(byte[] secretKey)", 

OR 

make it handle the seed correctly, for example by seeding SecureRandom with "seed" and then taking "sk" from it, like so:

```
public static int crypto_box_keypair_with_seed(byte[] pk, byte[] sk, byte[] seed)
{
    // create secret key randomly (default RNG of current platform)
    SecureRandom rng = new SecureRandom();
    byte[] random = new byte[crypto_secretbox_SECRETKEYBYTES];
    rng.nextBytes(random);
    
    // create more or less random number from seed
    SecureRandom rngSeeded = SecureRandom.getInstance("SHA1PRNG");
    rngSeeded.setSeed(seed);
    byte[] randomSeeded = new byte[crypto_secretbox_SECRETKEYBYTES];
    rngSeeded.nextBytes(randomSeeded);

    // XOR the two random numbers, forming the secret key
    for (byte b : random) {
        sk[i] = b ^ randomSeeded[i++];
    }
    
    return curve25519.crypto_scalarmult_base(pk, sk);
} 
```
PS: excuse me for taking this example from jNaCl.

This actually creates "random" randomly (default PRNG), then seeds the SHA1-PRNG with "seed" and gets a second random number "randomSeeded", finally XORing "random" and "randomSeeded" together, to form "sk". This was done because the default PRNG is sometimes better than SHA1-PRNG, sometimes worse, but in any case should we never solely rely on a deterministic seeding of the SHA1-PRNG. SHA1 was chosen, however, because it is widely believed to be secure, IF the seed is not compromised. By combining both methods (via XOR), we hopefully get the best of both worlds.

What do you think of this?
Cheers

**Comment by sequoiar** [comment]
@ryhaberecht we can use "new KeyPair()" to get secure secret key, if user can not provide secure seed.

**Comment by ryhaberecht** [comment]
Yes, **we** can, but how many drive-by-coders are going to look into the code to see whether they are supposed to provide a [common seed](https://en.wikipedia.org/wiki/Random_seed), or a perfectly random secret key?
I would suggest that the current name of the function strongly implies a seed, while actually requiring a random secret key.

**Comment by sequoiar** [comment]
@ryhaberecht agree change signature to keyPair_fromSecureSeed(...). and, let user provide secure seed.
