### ISSUE TITLE
Insecure PRNG

### ISSUE THREAD

**Issue by ott** [InstantWebP2P/tweetnacl-java#2]
tweetnacl-java uses `java.util.Random` which is not a CPRNG and thus is not suitable for cryptographic applications because it can be easily predicted. `java.security.SecureRandom` is CPRNG that is generally available on JVMs.

**Comment by sequoiar** [comment]
@ott has fixed as  tag 1.0.1 .thanks.

**Comment by ott** [comment]
Perhaps you should include a notice in the README file that notifies users of the library about the security vulnerability and that makes them aware that they should consider all their keys generated by the library and data encrypted with the library compromised.

**Comment by sequoiar** [comment]
good idea. just added it in README.md.
