### ISSUE TITLE
Can you please publish this library to Maven Central?

### ISSUE THREAD

**Issue by 4ig** [InstantWebP2P/tweetnacl-java#28]
Thank you for implementing this library! It's great! 
Is there a reason it is not published to Maven Central? Can I help in it in any way?

**Comment by Shpota** [comment]
If anyone needs it, I made a fork and [published it to Maven Central](https://github.com/sol4k/tweetnacl). 

Gradle

```
implementation 'org.sol4k:tweetnacl:0.1.5'
```

Maven

```xml
<dependency>
    <groupId>org.sol4k</groupId>
    <artifactId>tweetnacl</artifactId>
    <version>0.1.5</version>
</dependency>
```

**Comment by sequoiar** [comment]
@Shpota Not sure if you can open a pull request for it. thx.
