### ISSUE TITLE
running the tests "easily"

### ISSUE THREAD

**Issue by franks42** [InstantWebP2P/tweetnacl-java#3]
Hi Tom - thanks for the tweetnacl port - great work!!!

Not sure how you run the java tests in TweetNaclTest and TweetNaclFastTest...
I've added to TweetNaclTest.java:

    public static void main(String[] args) {
        TweetNaclTest t = new TweetNaclTest();
        t.start();
    }

and similar lines to the TweetNaclFastTest.java.

Then run the following from the command line in top directory:

$  mkdir out
$  javac -d out src/com/iwebpp/crypto/TweetNacl.java src/com/iwebpp/crypto/TweetNaclFast.java src/com/iwebpp/crypto/tests/TweetNaclTest.java  src/com/iwebpp/crypto/tests/TweetNaclFastTest.java src/com/iwebpp/crypto/tests/Log.java
$  java -cp out com.iwebpp.crypto.tests.TweetNaclTest
$  java -cp out com.iwebpp.crypto.tests.TweetNaclFastTest

Want to add those few lines to the TweetNaclTest.java, TweetNaclFastTest.java and the readme?

**Comment by sequoiar** [comment]
@franks42 please fork it, then send a pull request. thx.

**Comment by sequoiar** [comment]
@franks42 thx for your support. if you have bandwidth, please help add maven build file.
